/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e9bcb5",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "surface-variant": "#e2e2e2",
        "secondary-fixed-dim": "#cdc5be",
        "on-surface-variant": "#5f3f3a",
        "surface-container-low": "#f3f3f3",
        "surface-dim": "#dadada",
        "on-primary-fixed-variant": "#930100",
        "primary-container": "#e60000",
        "secondary-fixed": "#eae1d9",
        "on-background": "#1b1b1b",
        "background": "#f9f9f9",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed": "#e2e2e2",
        "tertiary": "#585a5a",
        "on-primary": "#ffffff",
        "tertiary-container": "#717272",
        "on-surface": "#1b1b1b",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#c00000",
        "secondary": "#635d57",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fff7f5",
        "on-primary-fixed": "#410000",
        "surface-container-high": "#e8e8e8",
        "on-secondary-container": "#69635d",
        "primary-fixed-dim": "#ffb4a8",
        "on-tertiary-fixed-variant": "#454747",
        "secondary-container": "#eae1d9",
        "on-secondary-fixed-variant": "#4b4640",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-container": "#f8f8f8",
        "tertiary-fixed-dim": "#c6c6c7",
        "outline": "#946e68",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdad4",
        "on-secondary-fixed": "#1f1b16",
        "primary": "#b70100",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb4a8",
        "inverse-surface": "#303030",
        "error": "#ba1a1a",
        "surface": "#f9f9f9",
        "brand-red": "var(--brand-red)",
        "creamy": "var(--creamy)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "lg": "48px",
        "margin": "24px",
        "md": "24px",
        "sm": "12px",
        "xl": "80px",
        "base": "8px",
        "gutter": "20px"
      },
      fontFamily: {
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
